config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  # Defines the root path route ("/")
  resources :lists, only: [:show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create,:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    @lists = List.all
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark.save
    redirect_to list_path(@list)
  end

  def show
    
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  def show
    @list = List.find(params[:id])
    @movies = Movie.all
  end

  def update
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="list banner shadow-lg p-3 mb-3 bg-body-tertiary rounded">
  <h2 class="shadow rounded fs-1 fw-bold"><%= @list.name %></h2>
</div>
<div class="container mt-2 mb-5">
  <%= simple_form_for [@list,@bookmark] do |f| %>
    <%= f.collection_select :movie_id, @movies, :id, :title, prompt: "Select a movie" %>
    <%= f.input :comment %>
    <%= f.button :submit , class: "btn btn-outline-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

  <div class="navbar d-flex bg-light px-3 ">
    <div class="me-auto p-2">
      <%= link_to "🍿", root_path ,class:"text-decoration-none mt-3 fs-4" %>
    </div>
    <div class="p-2 align-center">
      <%= link_to "My Lists", root_path ,class:"p-2 btn btn-outline-danger py-1 mt-2 py-1" %>
    </div>
      <div class="p-2 align-center">
        <%= link_to "Add list", new_list_path ,class:"p-2 btn btn-outline-warning py-1 mt-2 py-1" %>
      </div>
    </div>
  </div>

    <%= yield %>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

  </body>
</html>

app/views/lists/home.html.erb
<% if false %>
  <div class="container">
    <h1>Lists</h1>
    <% @lists.each do |list| %>
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= list.name %>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% list.bookmarks.each do |bookmark| %>
            <a class="dropdown-item fw-2" href="movies/<%= bookmark.movie.id %>"><%= bookmark.movie.title %>helloooo</a>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>


<%# <img src="https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1625&q=80" alt="cinema" width="100%" height="500rem"> %>
<div class="image banner shadow-lg p-3 mb-3 bg-body-tertiary rounded">
  <h2 class="shadow rounded fs-1 fw-bold">Save any kind of movies</h2>
</div>


<div class="container d-flex ">
  <div class="card rounded text-center show1 my-5 mx-3 shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="width: 18rem; height: 15rem;">
    <p>Classy</p>
  </div>
  <div class="card rounded text-center show2 my-5 mx-3 shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="width: 18rem; height: 15rem;">
    <p>Horror</p>
  </div>
  <div class="card rounded text-center show3 my-5 mx-3 shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="width: 18rem; height: 15rem;">
    <p>Nature</p>
  </div>
  <div class="card rounded text-center show4 my-5 mx-3 shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="width: 18rem; height: 15rem;">
    <p>Documentaries</p>
  </div>
  <%= link_to "Create a movie list", new_list_path,class: "btn btn-outline-secondary mt-3 text-center " ,style:"width: 16%; height: 10%;"%>
</div>

app/views/lists/index.html.erb
<div class="list banner shadow-lg p-3 mb-3 bg-body-tertiary rounded">
  <h2 class="shadow rounded fs-1 fw-bold">Your Own Netflix</h2>
</div>
<div class="container d-flex ">
  <% @lists.each do |list| %>
  <div class="card rounded text-center show1 my-5 mx-3 shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="width: 18rem; height: 15rem;">
    <%= link_to "#{list.name}",list_path(list.id), class:"text-decoration-none"%>
  </div>
  <% end %>
    <%= link_to "Create a movie list", new_list_path,class: "btn btn-outline-secondary mt-3 text-center " ,style:"width: 16%; height: 10%;"%>
</div>

app/views/lists/new.html.erb
<div class="list banner shadow-lg p-3 mb-3 bg-body-tertiary rounded">
  <h2 class="shadow rounded fs-1 fw-bold"><%= @list.name %></h2>
</div>
<div class="container mt-2 mb-5">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name  %>
    <%= f.button :submit ,class:"btn btn-outline-primary"%>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="list banner shadow-lg p-3 mb-3 bg-body-tertiary rounded">
  <h2 class="shadow rounded fs-1 fw-bold"><%= @list.name %></h2>
</div>
  <%= link_to "Add movie",new_list_bookmark_path(@list), class:"btn btn-outline-primary text end" %>
<div class="container d-flex">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card rounded text-center show1 my-5 mx-3 shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="width: 18rem; height: 15rem; position: relative;">
      <%= bookmark.movie.title %>
      <div style="position: absolute; bottom: 5px; right: 5px;">
        <%= link_to "Remove", list_bookmark_path(@list, bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-decoration-none  text-danger" %>
      </div>
    </div>
  <% end %>
</div>
<%= cl_image_tag("https://res.cloudinary.com/dhbrz1unb/image/upload/v1685809353/c0awsezia925ddu5sfwa.jpggit ",
      width: 400, height: 300, crop: :fill) %>

app/views/movies/show.html.erb
halo